[project]
name = "dota2hass"
version = "0.1.0"
description = "Add your description here"
requires-python = "==3.11.11"
dependencies = [
    "aiomqtt>=2.4.0",
    "dota2gsipy>=0.1.0",
    "fastapi>=0.120.0",
    "pydantic-settings>=2.12.0",
    "uvicorn>=0.38.0",
]
